/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverTripsTripIdRouteImport } from './routes/driver.trips.$tripId'
import { Route as DriverTripsNewRouteImport } from './routes/driver.trips.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTripsTripIdRoute = DriverTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTripsNewRoute = DriverTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/request': typeof RequestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/driver/': typeof DriverIndexRoute
  '/driver/trips/$tripId': typeof DriverTripsTripIdRoute
  '/driver/trips/new': typeof DriverTripsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/request': typeof RequestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/driver': typeof DriverIndexRoute
  '/driver/trips/$tripId': typeof DriverTripsTripIdRoute
  '/driver/trips/new': typeof DriverTripsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/request': typeof RequestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/driver/': typeof DriverIndexRoute
  '/driver/trips/$tripId': typeof DriverTripsTripIdRoute
  '/driver/trips/new': typeof DriverTripsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/onboarding'
    | '/request'
    | '/auth/callback'
    | '/driver/'
    | '/driver/trips/$tripId'
    | '/driver/trips/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/request'
    | '/auth/callback'
    | '/driver'
    | '/driver/trips/$tripId'
    | '/driver/trips/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/onboarding'
    | '/request'
    | '/auth/callback'
    | '/driver/'
    | '/driver/trips/$tripId'
    | '/driver/trips/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RequestRoute: typeof RequestRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/trips/$tripId': {
      id: '/driver/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/driver/trips/$tripId'
      preLoaderRoute: typeof DriverTripsTripIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/trips/new': {
      id: '/driver/trips/new'
      path: '/trips/new'
      fullPath: '/driver/trips/new'
      preLoaderRoute: typeof DriverTripsNewRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
  DriverTripsTripIdRoute: typeof DriverTripsTripIdRoute
  DriverTripsNewRoute: typeof DriverTripsNewRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
  DriverTripsTripIdRoute: DriverTripsTripIdRoute,
  DriverTripsNewRoute: DriverTripsNewRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RequestRoute: RequestRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
